name: Run Tests

on:
  workflow_dispatch:
  pull_request:
    types: [opened]
    branches: [main, develop, test-2]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Set PR Tag Environment variable
    steps:
      - name: set TAG PR Value step
        id: tag_pr
        uses: metis-data/metis-test-github-action@v1.8
      - name: print env var value
        env: 
          METIS_TAG_PR: ${{ steps.tag_pr.outputs.pr_tag  }} 
        run: echo "The time was $METIS_TAG_PR"
