name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        required: true

jobs:
  # This workflow contains multiple jobs
  build_cli:
    timeout-minutes: 4
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.5]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.5
          registry-url: 'https://registry.npmjs.org/'
          scope: '@metis-data'
      - name: Install dependencies
        run: |
          npm install
          lerna link
          lerna list
          lerna bootstrap
      - name: Build
        run: |
          lerna run --parallel build
      - name: Test
        run: |
          lerna run test
      - name: 'Set version to: ${{ inputs.version }}'
        run: |
          # Needed so we would be able to push a new tagged commit for the new version.
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"

          lerna version ${{ inputs.version }} --yes
      - name: Publish to NPM
        run: lerna --scope=@metis-data/base-interceptor --scope=@metis-data/sequelize-interceptor --scope=@metis-data/sequelize-express-interceptor exec npm publish -- --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
