name: E2E-TEST-JEST

on:
  workflow_dispatch:
  pull_request:
    types: [opened]
    branches: [main, develop, test-2]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: examples/prisma-express-example-airbases
    steps:
      - name: set TAG PR Value step
        id: tag_pr
        uses: metis-data/sql-queries-analyzer@v1
        with:
          metis_api_key: ePdc0lVx4S1EZsz9705Nl3prUtiz5OfX5nN4OfOy
          github_token: ${{ secrets.GITHUB_TOKEN}}
          target_url: https://dev.metisdata.io
      - name: checkout
        uses: actions/checkout@v3

      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: test
        env:
          METIS_EXPORTER_URL: https://ingest-stg.metisdata.io
          METIS_TAG_PR: ${{ steps.tag_pr.outputs.pr_tag  }}
          METIS_API_KEY: ePdc0lVx4S1EZsz9705Nl3prUtiz5OfX5nN4OfOy
          PG_CONNECTION_STRING: postgresql://postgres:Trustno1@database-2.cofhrj7zmyn4.eu-central-1.rds.amazonaws.com:5432/airbases?schema=postgres_air&connection_limit=10
        run: npm install && npm run generate &&  npm test

